version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      prisma:
        patterns:
          - prisma
          - "@prisma/*"
      better-auth:
        patterns:
          - better-auth
          - "@better-auth/*"
          - auth
    ignore:
      - dependency-name: prisma
        update-types: [version-update:semver-major]
      - dependency-name: "@prisma/*"
        update-types: [version-update:semver-major]
      - dependency-name: recharts
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
